### ISSUE TITLE
Support for lower versions of Android

### ISSUE THREAD

**Issue by nekofar** [itzikBraun/TutorialView#2]
I just wanted to know if is there any plan for support lower SDK versions?

**Comment by itzikBraun** [comment]
Hi nekofar, 

I don't think there should be a problem using the library with lower versions, I've set the min SDK in the build.gradle to 15 because i couldn't check it for lower versions. 

Would it be possible for you to change the min SDK in the gradle file and let me know if you have issues?

Thanks,
Itzik.
